# Generated by Django 5.1.7 on 2025-03-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='動物名稱')),
                ('age', models.IntegerField(verbose_name='年齡')),
                ('species', models.CharField(max_length=100, verbose_name='物種')),
                ('weight', models.FloatField(verbose_name='體重')),
            ],
        ),
    ]
