# Generated by Django 5.1.7 on 2025-03-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='館別名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='動物名稱')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身高')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='體重')),
                ('cup_size', models.CharField(blank=True, max_length=5, null=True, verbose_name='罩杯')),
                ('fee', models.IntegerField(blank=True, null=True, verbose_name='台費')),
                ('time_slot', models.CharField(blank=True, help_text="請輸入時段，每個時段用 '.' 隔開，例如：12.13.14.15.16.17.18.19.20", max_length=200, verbose_name='時段')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/', verbose_name='照片')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.hall', verbose_name='館別')),
            ],
        ),
    ]
