# Generated by Django 5.1.7 on 2025-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hall_animal_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='time_slot',
            field=models.CharField(blank=True, help_text="請輸入時段，每個時段用 '.' 隔開，例如：12.13.14.15.16.17.18.19.20", max_length=200, verbose_name='時段'),
        ),
    ]
