# Generated by Django 5.1.7 on 2025-03-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_animal_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='weight',
        ),
    ]
