# Generated by Django 5.1.7 on 2025-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_animal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='species',
        ),
        migrations.AddField(
            model_name='animal',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='台費'),
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(default='', max_length=100, verbose_name='身材'),
        ),
    ]
