# Generated by Django 5.1.7 on 2025-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_animal_age_remove_animal_species_animal_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='size',
        ),
        migrations.AddField(
            model_name='animal',
            name='cup_size',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='罩杯'),
        ),
        migrations.AddField(
            model_name='animal',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='身高'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='體重'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='台費'),
        ),
    ]
