# Generated by Django 5.1.7 on 2025-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_animal_size_animal_cup_size_animal_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='體重'),
        ),
    ]
